### ISSUE TITLE
fix email

### ISSUE THREAD

**Issue by dfridovi** [CLeARoboticsLab/CLeARoboticsLab.github.io#32]
https://github.com/CLeARoboticsLab/CLeARoboticsLab.github.io/blob/5765eaa5482e51c8546b17b423400231222f8cca/_people/Dongho_Lee.md?plain=1#L11

**Comment by leedh0124** [comment]
created a new pull request reflecting email changes and merged already!

**Comment by dfridovi** [comment]
great. pro tip: you can reference this issue in the PR description (e.g. "closes X") and then when you merge the PR, issue X will automatically close with a link to the PR

**Comment by leedh0124** [comment]
That's great :) Thanks for the tip!
