### ISSUE TITLE
nit: extra quote in email

### ISSUE THREAD

**Issue by dfridovi** [CLeARoboticsLab/CLeARoboticsLab.github.io#33]
https://github.com/CLeARoboticsLab/CLeARoboticsLab.github.io/blob/484e760b1eabdc7bb6112bfa22107125ec9a9536/_people/jaehan_im.md?plain=1#L12

**Comment by dfridovi** [comment]
@iamjaehan are you planning to fix?

**Comment by iamjaehan** [comment]
@dfridovi Sorry, I will fix now.

**Comment by dfridovi** [comment]
No worries. Easy to miss theseSent from my iPhoneOn Sep 22, 2023, at 7:05 PM, Jaehan Im ***@***.***> wrote:﻿
@dfridovi Sorry, I will fix now.
